version: "3"

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    expose:
      - "3100:3100"
    networks:
      - loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      # Add any other volumes or configurations as needed for Loki
  
  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml    
    depends_on:
      - loki    
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      # Add any other volumes or configurations as needed for Grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

networks:
  loki:
    external: true
