# Use an official Node.js runtime as a parent image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /app

COPY server /app/server

# Copy package.json and package-lock.json to the working directory
COPY server/package*.json ./

# Install app dependencies
RUN npm install

# Bundle app source
COPY server .

# Expose port 5000 to the outside world
EXPOSE 5000

# Define the command to run your app
CMD ["npm", "start"]
