name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Display BuildKit version
        run: docker buildx version

      - name: Build App Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker buildx create --use --name mybuilder --driver docker-container
          docker buildx build --platform linux/amd64,linux/arm64 -t docker.io/hannahbrownson/check-it-out-app:latest .
          
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push docker.io/hannahbrownson/check-it-out-app:latest

      - name: Build and Push Server Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t docker.io/hannahbrownson/check-it-out-server:latest .

          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push docker.io/hannahbrownson/check-it-out-server:latest
